### ISSUE TITLE
Quarto + Julia

### ISSUE THREAD

**Issue by jeremiahpslewis** [Lakens/statistical_inferences#11]
Love your book!

Without wanting to commit to anything *yet*, would you entertain a PR which used quarto to add Julia snippets as tabs for those who don’t use R? Maybe someone would come along and throw in Python as well.

https://quarto.org/docs/interactive/layout.html#tabset-panel

**Comment by Lakens** [comment]
I understand the idea, but it's difficult, because I could not evaluate whether the code works. I've seen people create resources 'translating' a text to different languages, but not having all languages in one online book. There might be good solutions, but, I Am not sure what they would look like, and having multiple blocks of code in different languages is a lot of scrolling.
